// src/scripts/apps/CategoryApp.svelte
<script lang="ts">
  import ApplicationForm, { type WithApplicationFormProps } from "../components/ApplicationForm.svelte";
  import FormGroup from "../components/FormGroup.svelte";
  import { getContext } from "svelte";
  import type { Consumer } from "../types";

  type CategoryAppProps = WithApplicationFormProps<{
    category: Downtime.Category;
  }>;

  const { category: categoryProps, onChange }: CategoryAppProps = $props();

  const category = $state<Downtime.Category>({
    id: foundry.utils.randomID(),
    name: "",
    description: "",
  });

  $effect(() => {
    Object.assign(category, categoryProps);
  });
</script>

<ApplicationForm class="standard-form downtime-dnd5e-form" {onChange}>
  <div class="dialog-content standard-form">
    <input name="id" type="hidden" value={category.id} />
    <FormGroup label="Name">
      <input type="text" name="name" bind:value={category.name} />
    </FormGroup>

    <FormGroup label="Description">
      <textarea name="description" bind:value={category.description}></textarea>
    </FormGroup>
  </div>
</ApplicationForm>

// src/scripts/apps/CategoryApp.vue
<script setup lang="ts">
import { computed, reactive, watch } from 'vue';
import FormGroup from '../components/FormGroup.vue'
import CONSTANTS from '../constants';

const props = defineProps<{
    category:Downtime.Category
}>()

const category = reactive<Downtime.Category>({
    id: foundry.utils.randomID(),
    description: '',
    name: ''
})

watch(() => props.category, (newVal) => {
    Object.assign(category, props.category)
}, {immediate:true, deep:true})
</script>

<template>
    <div class="dialog-content standard-form">
        <input name="id" type="hidden" :value="category.id"></input>
        <FormGroup label="Name">
            <input type="text" name="name" v-model="category.name" ></input>
        </FormGroup>

        <FormGroup label="Description">
            <textarea name="description" v-model="category.description"></textarea>
        </FormGroup>
    </div>
</template>
