// src/scripts/apps/TrackedItemApp.vue
<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue';
import FormGroup from '../components/FormGroup.vue'
import DndProgress from '../components/DndProgress.vue'
import CONSTANTS from '../constants';
import { localize } from '../utils/localize';

const props = defineProps<{
    categories: Downtime.Category[],
    dropdownOptions: {abilities: {value: string, type: string, label: string}[], skills: {value: string, type: string, label: string}[], tools: {value: string, type: string, label: string}[]}
    item: Downtime.TrackedItem
}>()

const skills = computed(() => props.dropdownOptions.skills)
const abilities = computed(() => props.dropdownOptions.abilities)
const tools = computed(() => props.dropdownOptions.tools)

const HINT_MAP = {
    FIXED: `ProgressionStyleFixedHelp`,
    ABILITY: `ProgressionStyleAbilityCheckHelp`,
    SKILL: `ProgressionStyleSkillCheckHelp`,
    TOOL: `ProgressionStyleToolCheckHelp`,
    MACRO: `ProgressionStyleMacroHelp`,
} as const


const form = reactive<Omit<Downtime.TrackedItem, 'changes'|'schemaVersion'>>({
    id: foundry.utils.randomID(),
    name: "",
    img: "icons/svg/book.svg",
    hidden: false,
    category: "",
    description: "",
    progress:0,
    progressionStyle: "ABILITY",
    dc: undefined,
    completionAt: 300,
    macro: ""
})

watch(() => props.item, (newVal) => {
    Object.assign(form, newVal)
}, {deep:true, immediate: true})

const hint = computed(() => localize(`${CONSTANTS.MODULE_ID}.${HINT_MAP[form.progressionStyle]}`))

const macrosId = computed(() => `${CONSTANTS.MODULE_ID}_MACROS_${Math.random().toString(16)}`)

const macros = game.macros.contents.map(x=>x.name)

const validMacro = ref(false)
const checkMacro = () => validMacro.value = !!game.macros.getName(form.macro)
const openMacro = () => game.macros.getName(form.macro)?.sheet?.render(true)

</script>

<template>
    <div class="dialog-content standard-form">
        <fieldset>
            <legend>Basic Details</legend>
        <FormGroup label="Id">
            <input type="text" name="id" v-model="form.id" readonly ></input>
        </FormGroup>

        <FormGroup label="Name">
            <input type="text" name="name" v-model="form.name" ></input>
        </FormGroup>

        <FormGroup label="Image">
            <file-picker name="img" type="image">
                <input class="image" type="text" placeholder="path/to/file.ext" v-model="form.img">
                <button class="fa-solid fa-file-import fa-fw icon" type="button" data-tooltip="FILES.BrowseTooltip"
                    aria-label="FILES.BrowseTooltip" tabindex="-1"></button>
            </file-picker>
        </FormGroup>

        <FormGroup label="Hidden from players?">
            <input type="checkbox" name="hidden" v-model="form.hidden">
        </FormGroup>

        <FormGroup label="Category">
            <select name="category" v-model="form.category">
                <option value="" selected>None</option>
                <option v-for="cat of categories" :value="cat.id" :key="cat.id">{{ cat.name }}</option>
            </select>
        </FormGroup>

        <FormGroup label="Description">
            <textarea name="description" v-model="form.description" rows="2"></textarea>
        </FormGroup>

        </fieldset>


        <fieldset>
            <legend>Type</legend>
            <FormGroup label="Type" :hint="hint">
                <select name="progressionStyle" v-model="form.progressionStyle">
                    <option value="FIXED">Fixed Value</option>
                    <option value="ABILITY">Ability Check</option>
                    <option value="SKILL">Skill Check</option>
                    <option value="TOOL">Tool Check</option>
                    <option value="MACRO">Macro</option>
                </select>
            </FormGroup>

            <FormGroup label="Skill" v-if="form.progressionStyle === 'SKILL'">
                <select name="skill" v-model="form.skill">
                    <option v-for="skill of skills" :value="skill.value">{{ skill.label }}</option>
                </select>
            </FormGroup>

            <FormGroup label="Tool" v-if="form.progressionStyle === 'TOOL'">
                <select name="tool">
                    <option v-for="tool of tools" :value="tool.value">{{ tool.label }}</option>
                </select>
            </FormGroup>

            <FormGroup label="Ability" v-if="form.progressionStyle === 'ABILITY'">
                <select name="ability">
                    <option v-for="ability of abilities" :value="ability.value">{{ ability.label }}</option>
                </select>
            </FormGroup>

            <FormGroup label="Fixed" v-if="form.progressionStyle === 'FIXED'">
                <input type="text" name="fixed"/>
            </FormGroup>

            <template v-if="form.progressionStyle === 'MACRO'">
                <FormGroup label="Macro Name">
                    <input type="text" name="macro" v-model="form.macro" :list="macrosId" @input="() => checkMacro()"></input>
                    <button v-if="validMacro" @click.prevent="() => openMacro()">Open</button>
                </FormGroup>
                <datalist :id="macrosId">
                    <option v-for="macroName of macros" :value="macroName"></option>
                </datalist>
            </template>
                    <FormGroup label="Check DC (Optional)" v-if="!['MACRO','FIXED'].includes(form.progressionStyle)">
            <input type="number" name="dc" v-model="form.dc" min="1" max="30">
        </FormGroup>
        </fieldset>


        <fieldset>
            <legend>Progression</legend>
        <FormGroup label="Current Progress">
            <input type="number" name="progress"  min="0" :max="form.completionAt" v-model.number="form.progress">
        </FormGroup>

        <FormGroup label="Completion Target">
            <input type="number" name="completionAt" min="0" v-model.number="form.completionAt">
        </FormGroup>

        <DndProgress style="width: 100%;" :value="form.progress" :max="form.completionAt"/>
        </fieldset>
    </div>
</template>

// src/scripts/apps/TrackedItemApp.svelte
<script lang="ts">
  import FormGroup from "../components/FormGroup.svelte";
  import DndProgress from "../components/DndProgress.svelte";
  import CONSTANTS from "../constants";
  import { localize } from "../utils/localize";
  import type { ObjectUnionMerged } from "../types";
  import { pluck } from "it-al";
  import ApplicationForm, { type WithApplicationFormProps } from "../components/ApplicationForm.svelte";

  type TrackedItemAppProps = WithApplicationFormProps<{
    categories: Downtime.Category[];
    dropdownOptions: Downtime.DropdownOptions;
    item: Downtime.TrackedItem;
  }>;

  const { categories, dropdownOptions, item, onChange }: TrackedItemAppProps = $props();

  const HINT_MAP = {
    FIXED: `ProgressionStyleFixedHelp`,
    ABILITY: `ProgressionStyleAbilityCheckHelp`,
    SKILL: `ProgressionStyleSkillCheckHelp`,
    TOOL: `ProgressionStyleToolCheckHelp`,
    MACRO: `ProgressionStyleMacroHelp`,
  } as const;

  const skills = $derived(dropdownOptions.skills);
  const abilities = $derived(dropdownOptions.abilities);
  const tools = $derived(dropdownOptions.tools);

  const form = $state<Omit<ObjectUnionMerged<Downtime.TrackedItem>, "changes" | "schemaVersion">>({
    id: foundry.utils.randomID(),
    name: "",
    img: "icons/svg/book.svg",
    hidden: false,
    category: "",
    description: "",
    chat_icon: "",
    progress: 0,
    progressionStyle: "ABILITY",
    dc: undefined,
    completionAt: 300,
    macroName: "",
    ability: "str",
    skill: "ath",
    tool: "",
    fixedIncrease: 1,
  });

  $effect(() => {
    Object.assign(form, item);
  });

  const hint = $derived(localize(`${CONSTANTS.MODULE_ID}.${HINT_MAP[form.progressionStyle]}`));
  const id = $props.id();
  const macrosId = $derived(`${CONSTANTS.MODULE_ID}_MACROS_${id}`);

  const macros = pluck(game.macros.contents, "name");

  let validMacro = $state(false);

  const checkMacro = () => {
    if (!form.macroName || form.progressionStyle !== "MACRO") {
      validMacro = false;
      return;
    }
    validMacro = !!game.macros.getName(form.macroName);
  };
  const openMacro = (e: MouseEvent) => {
    e.preventDefault();
    if (!form.macroName || form.progressionStyle !== "MACRO") return;
    game.macros.getName(form.macroName)?.sheet?.render(true);
  };
</script>

<ApplicationForm {onChange}>
  <fieldset>
    <legend>Basic Details</legend>
    <FormGroup label="Id">
      <input type="text" name="id" bind:value={form.id} readonly />
    </FormGroup>

    <FormGroup label="Name">
      <input type="text" name="name" bind:value={form.name} />
    </FormGroup>

    <FormGroup label="Image">
      <file-picker name="img" type="image">
        <input class="image" type="text" placeholder="path/to/file.ext" bind:value={form.img} />
        <button
          class="fa-solid fa-file-import fa-fw icon"
          type="button"
          data-tooltip="FILES.BrowseTooltip"
          aria-label="FILES.BrowseTooltip"
          tabindex="-1"
        ></button>
      </file-picker>
    </FormGroup>

    <FormGroup label="Hidden from players?">
      <input type="checkbox" name="hidden" bind:value={form.hidden} />
    </FormGroup>

    <FormGroup label="Category">
      <select name="category" bind:value={form.category}>
        <option value="" selected>None</option>
        {#each categories as category}
          <option value={category.id}>{category.name}</option>
        {/each}
      </select>
    </FormGroup>

    <FormGroup label="Description">
      <textarea name="description" bind:value={form.description} rows="2"></textarea>
    </FormGroup>
  </fieldset>

  <fieldset>
    <legend>Type</legend>
    <FormGroup label="Type" {hint}>
      <select name="progressionStyle" bind:value={form.progressionStyle}>
        <option value="FIXED">Fixed Value</option>
        <option value="ABILITY">Ability Check</option>
        <option value="SKILL">Skill Check</option>
        <option value="TOOL">Tool Check</option>
        <option value="MACRO">Macro</option>
      </select>
    </FormGroup>

    {#if form.progressionStyle === "SKILL"}
      <FormGroup label="Skill">
        <select name="skill" bind:value={form.skill}>
          {#each skills as skill}
            <option value={skill.value}>{skill.label}</option>
          {/each}
        </select>
      </FormGroup>
    {/if}

    {#if form.progressionStyle === "TOOL"}
      <FormGroup label="Tool">
        <select name="tool">
          {#each tools as tool}
            <option value={tool.value}>{tool.label}</option>
          {/each}
        </select>
      </FormGroup>
    {/if}

    {#if form.progressionStyle === "ABILITY"}
      <FormGroup label="Ability">
        <select name="ability">
          {#each abilities as ability}
            <option value={ability.value}>{ability.label}</option>
          {/each}
        </select>
      </FormGroup>
    {/if}

    {#if form.progressionStyle === "FIXED"}
      <FormGroup label="Fixed">
        <input type="text" name="fixed" />
      </FormGroup>
    {/if}

    {#if form.progressionStyle === "MACRO"}
      <FormGroup label="Macro Name">
        <input type="text" name="macro" bind:value={form.macroName} list={macrosId} oninput={checkMacro} />
        {#if validMacro}
          <button onclick={openMacro}>Open</button>
        {/if}
      </FormGroup>
      <datalist id={macrosId}>
        {#each macros as macroName}
          <option value={macroName}></option>
        {/each}
      </datalist>
    {/if}

    {#if !["MACRO", "FIXED"].includes(form.progressionStyle)}
      <FormGroup label="Check DC (Optional)">
        <input type="number" name="dc" bind:value={form.dc} min="1" max="30" />
      </FormGroup>
    {/if}
  </fieldset>

  <fieldset>
    <legend>Progression</legend>
    <FormGroup label="Current Progress">
      <input type="number" name="progress" min="0" max={form.completionAt} bind:value={form.progress} />
    </FormGroup>

    <FormGroup label="Completion Target">
      <input type="number" name="completionAt" min="0" bind:value={form.completionAt} />
    </FormGroup>

    <DndProgress style="width: 100%;" value={form.progress} max={form.completionAt} />
  </fieldset>
</ApplicationForm>
