// src/scripts/components/DndTableCell.vue
<script lang="ts" setup>
const props = defineProps<{
    column: {
        id: string,
        width: number,
        formatted: string
    }
}>()
</script>

<template>
    <div class="item-detail" :class="`item-${props.column.id}`" :data-column-id="props.column.id" :style="{width: column.formatted}" >
        <slot />
    </div>
</template>

// src/scripts/components/DndTableCell.svelte
<script lang="ts">
  import type { ColumnNormalized } from "./DndTable.svelte";

  type DndTableCellProps = {
    column: ColumnNormalized;
    children?: Function;
  };

  let { column, children }: DndTableCellProps = $props();
</script>

<div class="item-detail item-{column.id}" data-column-id={column.id} style="width: {column.formatted}">
  {@render children?.()}
</div>
