// src/scripts/components/DndTableRow.vue
<script setup lang="ts">
import { MaybeGetter, TableInjectionKey } from '../types';
import { inject} from 'vue'

const props = defineProps<{}>()

const { columns, columnsById, name } = inject(TableInjectionKey)!

defineSlots<{
    default():void
}& Record<`cell(${string})`, (props: {
        column: {
            id: string,
            width: number,
            formatted: string
    }
}) => any>>()

</script>

<template>
    <li class="item">
        <div class="item-row">
            <slot />
            <slot v-for="[id, col] of columnsById" :name="`cell(${id})`" :column="col" >
                Unslotted {{ id }}
            </slot>
        </div>
    </li>
</template>

<style scoped>
.item-row {
    width: 100%;
}
</style>

// src/scripts/components/DndTableRow.svelte
<script lang="ts">
  import { getContext, type Snippet } from "svelte";
  import { type TableContextValue, TableInjectionKey, type MaybeGetter } from "../types";
  import type { ColumnNormalized } from "./DndTable.svelte";

  type DndTableRow = {
    children?: Function;
    [name: `cell__${string}`]: Snippet<[{ column: ColumnNormalized }]>;
  };

  let { children, ...props }: DndTableRow = $props();

  const { columnsById } = getContext<TableContextValue>(TableInjectionKey);
</script>

<li class="item">
  <div class="item-row">
    {@render children?.()}
    {#each columnsById() as [id, column]}
      {@const cellId = props[`cell__${id}` as const]}
      {#if cellId}
        {@render cellId({ column })}
      {:else}
        Unslotted {id}
      {/if}
    {/each}
  </div>
</li>

<style>
  .item-row {
    width: 100%;
  }
</style>
