// src/scripts/components/FormButtons.vue
<script setup lang="ts">
import { computed, toValue, MaybeRefOrGetter } from "vue";
import { localize } from "../utils/localize";

const props = defineProps<{
    buttons: Record<
        string,
        foundry.applications.api.DialogV2.Button & { hide?: () => unknown; disabled?: MaybeRefOrGetter<boolean> }
    >;
}>();

const defaultDefined = computed(() => Object.values(props.buttons).some((btn) => btn.default));
const buttons = computed(() =>
    Object.values(props.buttons)
        .filter((btn) => !btn.hide?.())
        .map((btn, index) => ({
            ...btn,
            default: index === 0 && !defaultDefined.value ? true : btn.default,
            label: localize(btn.label as Downtime.I18nKeys),
        })),
);
</script>

<template>
    <button
        v-for="btn of buttons"
        :key="btn.label"
        :data-action="btn.action"
        :type="btn.type"
        :class="btn.class"
        :style="btn.style"
        :disabled="toValue(btn.disabled)"
    >
        <i v-if="btn.icon" :class="btn.icon"></i>
        {{ btn.label }}
    </button>
</template>

// src/scripts/components/FormButtons.svelte
<script lang="ts">
  import type { MaybeGetter } from "../types";
  import { toValue } from "../utils/toValue";
  import { localize } from "../utils/localize";

  export type ExtendedButton = foundry.applications.api.DialogV2.Button & {
    hide?: () => unknown;
    disabled?: MaybeGetter<boolean>;
  };

  type FormButtonsProps = {
    buttons: ExtendedButton[];
  };

  let { buttons: buttonsProp = [] }: FormButtonsProps = $props();

  const defaultDefined = $derived(() => buttonsProp.some((btn) => btn.default));

  const buttons = $derived(
    buttonsProp
      .filter((btn) => !btn.hide?.())
      .map((btn, index) => ({
        ...btn,
        default: index === 0 && !defaultDefined ? true : btn.default,
        label: localize(btn.label as Downtime.I18nKeys),
        disabled: toValue(btn.disabled ?? false),
        style: Object.values(btn.style ?? {})
          .map(([key, value]) => `${key}: ${value};`)
          .join(""),
      }))
  );
</script>

{#each buttons as button}
  <button
    class={button.class}
    type={button.type}
    style={button.style}
    disabled={button.disabled}
    data-action={button.action}
  >
    {#if button.icon}
      <i class={button.icon}></i>
    {/if}
    {button.label}
  </button>
{/each}
